# Bouffalo Lab MCU SDK Project Configuration for Sipeed M1s Dock (BL808)
set(CONFIG_CHIP bl808)
set(CONFIG_BOARD bl808_m1s_dock)
set(CONFIG_CPU d0)

# Enable Hardware Peripherals
set(CONFIG_BFLB_MTIMER 1)
set(CONFIG_BFLB_GPIO 1)
set(CONFIG_BFLB_SPI 1)
set(CONFIG_BFLB_DMA 1)
set(CONFIG_BFLB_I2C 1)
set(CONFIG_BFLB_CAM 1)
set(CONFIG_BFLB_UART 1)

# Optimization Flags
set(CONFIG_OPTIMIZATION_LEVEL -O2)
