# Bouffalo Lab MCU SDK Project Configuration for Sipeed M1s Dock (BL808)
set(CONFIG_CHIP bl808)
set(CONFIG_BOARD bl808dk)
set(CONFIG_CPU m0)


# C Runtime & Printf Float Support
set(CONFIG_NEWLIB 0)
set(CONFIG_NEWLIB_STANDARD 0)
set(CONFIG_VSNPRINTF_FLOAT 1)
set(CONFIG_VSNPRINTF_FLOAT_EX 1)

# Hardware Peripherals
set(CONFIG_BSP_IMAGE_SENSOR 1)
set(CONFIG_BSP_CSI 1)

# Optimization Flags
set(CONFIG_OPTIMIZATION_LEVEL -O2)


